--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WhiteGrouse/TestPlugin
build-by-default: true
branches:
- master
projects:
  TestPlugin:
    path: ""
    libs:
    - src: Flowy
    - src: Standard
...
